### ISSUE TITLE
Upload nightly (weekly) builds to anaconda.org

### ISSUE THREAD

**Issue by mattip** [MacPython/openblas-libs#100]
It would be good to reduce the lag between OpenBLAS changes and getting them tried out in SciPy/NumPy. The first step in that would be to upload like NumPy/SciPy/matplotlib do to https://anaconda.org/scientific-python-nightly-wheels/.

xref @honno @steppi

**Comment by rgommers** [comment]
Cc @tupui is one of the admins for that Anaconda bucket - he can help with creating a token that's needed for uploading.

**Comment by tupui** [comment]
The request is approved and we can move forward. Please get in touch (privately) to share the Anaconda handles of the admins for this.

(We are discussing with Anaconda's team right now about our security concerns, etc. So things should hopefully improve.)

**Comment by mattip** [comment]
The scheduled linux runs [look good](https://anaconda.org/multibuild-wheels-staging/openblas-libs/files). For some reason the macos ones apparently did not pick up the `NIGHTLY` environment variable, and built 0.3.23 tarballs.

**Comment by mattip** [comment]
Reopening to change the frequency to once-a-week, and to add in the travis builds

**Comment by mattip** [comment]
Additionally, we should move the [upload target](https://github.com/MacPython/openblas-libs/blob/a64e515f2db3d226c1bfa603050b99ee517d18e3/.github/workflows/multibuild.yml#L139) from https://anaconda.org/multibuild-wheels-staging/openblas-libs/ to https://anaconda.org/scientific-python-nightly-wheels/openblas-libs

**Comment by steppi** [comment]
> Additionally, we should move the [upload target](https://github.com/MacPython/openblas-libs/blob/a64e515f2db3d226c1bfa603050b99ee517d18e3/.github/workflows/multibuild.yml#L139) from https://anaconda.org/multibuild-wheels-staging/openblas-libs/ to https://anaconda.org/scientific-python-nightly-wheels/openblas-libs

does just mean replacing

```
--no-progress -u multibuild-wheels-staging
```

with

```
--no-progress -u scientific-python-nightly-wheels
```
?

**Comment by mattip** [comment]
> does just mean replacing

yes, but the proper token is needed as well. I think @honno has permissions needed to make this happen

**Comment by steppi** [comment]
> > does just mean replacing
> 
> yes, but the proper token is needed as well. I think @honno has permissions needed to make this happen

Thanks. Got it.

**Comment by tupui** [comment]
@honno has permissions but I need to make the first upload. Please coordinate this next week with me 😃

**Comment by honno** [comment]
@tupui to clarify, would it be fine to have the nightly builds just be uploaded to same filename for `scientific-python-nightly-wheels`? e.g. `openblas-HEAD-musllinux_1_1_x86_64.tar.gz`, `openblas-HEAD-manylinux2014_x86_64.tar.gz`, 
`openblas64_-HEAD-musllinux_1_1_x86_64.tar.gz`, etc..

**Comment by tupui** [comment]
Sure we don't have any requirements for now

**Comment by mattip** [comment]
Closing, there are now weekly tarballs at the new locations

**Comment by tupui** [comment]
Yay 🎉 thank you all this is great!
