### ISSUE TITLE
`anaconda-client` is broken due to `urllib3` v2 release

### ISSUE THREAD

**Issue by honno** [MacPython/openblas-libs#102]
See https://github.com/Anaconda-Platform/anaconda-client/issues/654. Found this whilst playing around CI on my own fork, where the `multibuild.yml` workflow currently fails uploading the tarballs because of this. I assume this hasn't been a problem here yet because `urllib3`/`anaconda-client` is cached by GitHub Actions.

We might want to pin `urllib3<2.0`... or rather, just `pip install urllib3<2.0` before this line in our workflow

https://github.com/MacPython/openblas-libs/blob/062f1f6e3ff102287bae00833e9ea245a9f68d61/.github/workflows/multibuild.yml#L122

Maybe `anaconda-client` will fix this issue soon, just thought I'd open a issue for posterity's sake.

**Comment by charris** [comment]
> pip install urllib3<2.0 before this line in our workflow

That works, see https://github.com/numpy/numpy/pull/24044.
