### ISSUE TITLE
HEAD build is not building the correct commit

### ISSUE THREAD

**Issue by mattip** [MacPython/openblas-libs#108]
~Any build that is not directly from a tag should have `dev` in the version or some other way to get more appropriate information. Currently, `openblas_get_config()` returns something like `OpenBLAS 0.3.23  USE64BITINT DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=64` even for builds that are not exactly `0.3.23`. It would be nice if it were `OpenBLAS 0.3.24-dev  ...`. @martin-frbg is there a way to do that in the `make` command`?~

OpenBLAS is not the problem, we are not properly checking out the commit we want

**Comment by martin-frbg** [comment]
It should be doing this already (VERSION is defined at build time by the toplevel CMakeLists.txt and Makefile.rule). Maybe your build doesn't because you cherry-picked some PRs on top of a tagged release or something like that ?

**Comment by martin-frbg** [comment]
btw it is 0.3.23.dev for anything between 23 and 24, although .24-dev might make at least as much sense, I "inherited" that naming scheme

**Comment by mattip** [comment]
Strange. The [builds for the current commit](https://anaconda.org/multibuild-wheels-staging/openblas-libs/v0.3.23-246-g3d31191b/download/openblas64_-v0.3.23-246-g3d31191b-manylinux2014_x86_64.tar.gz), after #101, have `OpenBLAS 0.3.23.dev ...`. The builds for what [should be HEAD](https://anaconda.org/multibuild-wheels-staging/openblas-libs/HEAD/download/openblas64_-HEAD-manylinux2014_x86_64.tar.gz) have `OpenBLAS 0.3.23 ...`. I wonder if building the HEAD of develop somehow gets the wrong version? Or maybe that [CI job](https://github.com/MacPython/openblas-libs/actions/runs/5565028502/jobs/10165057638) is not doing what I think it should be doing? 

Indeed, looking at the [build log](https://github.com/MacPython/openblas-libs/actions/runs/5565028502/jobs/10165057638#step:7:183) I see `git checkout v0.3.23`. This is coming from [`git checkout $OPENBLAS_COMMIT`](https://github.com/MacPython/openblas-libs/blob/a64e515f2db3d226c1bfa603050b99ee517d18e3/tools/build_openblas.sh#L52). @honno is that environment variable being reset to `develop` when running a scheduled build?

**Comment by mattip** [comment]
I think when PR #103 was modified to a single yaml file, instead of two separate ones,  I did not properly review which commit was used. The call to [`clean_code`](https://github.com/MacPython/openblas-libs/blob/a64e515f2db3d226c1bfa603050b99ee517d18e3/.github/workflows/multibuild.yml#L112) should use `develop` if it is a nightly build
