### ISSUE TITLE
OpenBLAS wheels are bundling libquadmath - licence points

### ISSUE THREAD

**Issue by andyfaff** [MacPython/openblas-libs#114]
I had a root around in the `scipy-openblas32` and `scipy-openblas64` wheels. They both bundle libquadmath. As far as I can tell `libquadmath` is licenced with LGPL.

- the libquadmath licence doesn't seem to be distributed with the wheel, should it be?
- What are the implications of bundling libquadmath on the overall licence of the wheel (and for packages that may link with the libraries within the wheel)?

**Comment by mattip** [comment]
Good points. The license in the wheel should be bundling the other licenses like [numpy does](https://github.com/numpy/numpy/blob/c64da5f6e3cbc417992a453e99eeb1b8f1cd2edc/tools/wheels/cibw_before_build.sh#L6). As for libquadmath, I see the current numpy wheels are bundling it, and have the same issue. The proper text should be added to the `LICENSE_*.txt` files.

**Comment by mattip** [comment]
Closing, the wheel includes the proper licenses.
