### ISSUE TITLE
Allow an argument to `get_pkg_config`

### ISSUE THREAD

**Issue by mattip** [MacPython/openblas-libs#133]
The wheel can be used in two scenarios:
- in a project which will depend on `import scipy_openblas64` to load the shared object into the executable and make the symbols available without the runtime loader needing to find the shared object
- in a project which will not depend on the wheel at runtime, so it will have to ship the shared object and it can be loaded at runtime via a `NEEDED` directive in the shared object that consumes the symbols

The second method is the one currently used by NumPy/SciPy. The difference between the two is
- The first options requires something like the `_distributor_init.py` trick to call `import scipy_openblas at runtime. It also requires that the `scipy-openblas.pc` file have an empty `Libs:` line (on posix).
- The second option will use something like `auditwheel` to pack the shared object into the project wheel, so it needs a proper `Libs: -L${libdir} -l scipy_openblas64_` line in the `scipy-openblas.pc` file

I think this can be resolved by adding an argument to `get_pkg_config()` to specify which line to create. Any good thoughts for what that argument should be called?

**Comment by mattip** [comment]
xref https://github.com/numpy/numpy/pull/25732#issuecomment-1921304668

**Comment by mattip** [comment]
`full_libs`?

**Comment by rgommers** [comment]
NumPy/SciPy use the second option, so that should be the default behavior I think. To avoid the `-lscipy_openblas64_` line, maybe something like `use_preloading`?
