### ISSUE TITLE
Wheels uploaded to https://anaconda.org/scientific-python-nightly-wheels/scipy-openblas32 are unusable

### ISSUE THREAD

**Issue by mattip** [MacPython/openblas-libs#139]
The wheel uploads are unusable, see numpy/numpy#25849 and scientific-python/upload-nightly-action#65. Perhaps moving to the tried-and-true github action instead of using our own upload would solve the problem.

**Comment by matthewfeickert** [comment]
While we're happy to try and help with the migration, is it established that the metadata included with the wheels is correct?

**Comment by matthewfeickert** [comment]
Things seem resolved now following @mattip triggering a nightly build post https://github.com/MacPython/openblas-libs/pull/140

c.f. https://github.com/numpy/numpy/issues/25849#issuecomment-1958830247

:+1:

**Comment by mattip** [comment]
Great. Closing.
