### ISSUE TITLE
Shrink x86_64 blas library size

### ISSUE THREAD

**Issue by mattip** [MacPython/openblas-libs#144]
As @martin-frbg [says in a comment elsewhere](https://github.com/numpy/numpy/issues/24905#issuecomment-1981062320)

> Given that there never were Macs with AMD processors, or (AFAIK) with AVX-512, you could reduce the size of your library build by adding DYNAMIC_LIST="CORE2 NEHALEM SANDYBRIDGE HASWELL", removing the dedicated BLAS kernels for 10 irrelevant cpus (if you don't already do this). Probably no longer worth it for you, but I guess I should add this as the default for x86_64 builds with OSNAME=Darwin...

**Comment by mattip** [comment]
I wonder what else we could do to tweak the dynamic kernels we ship. Fro instance, can we boost the minimum x86_64 on linux from [PRESCOTT}(https://github.com/MacPython/openblas-libs/blob/199d5e560a8841c38b555b00ca887cc5b6cd0e43/tools/build_steps.sh#L123)?

**Comment by rgommers** [comment]
It would be worth summarizing what we are actually building in this repo I think. It looks like we are using `DYNAMIC_ARCH=1 TARGET=PRESCOTT`, but it's not exactly clear to me from the OpenBLAS README what that does. I am guessing "all architectures from PRESCOTT up" - but if so, that seems a little excessive?

Other questions I'd have:
- What is the binary size impact of including/excluding a single architecture?
- What happens on non-included architectures? Does it use the next-older target? If so, what performance is left on the table on average?

**Comment by martin-frbg** [comment]
TARGET=PRESCOTT in combination with DYNAMIC_ARCH is "use compiler options for Prescott when compiling the common code (thread setup, interfaces, LAPACK)", DYNAMIC _ARCH on x86_64 is a list of about 15 Intel and AMD cpus unless you specify your own subset via DYNAMIC_LIST. Can't give an exact answer for the per-model overhead, but it is something like 50 BLAS kernel objects plus parameters and function pointer table setup. Any non-included target gets supported by the next best available - again no exact figures but I'd guess at most 10 percent performance loss unless the fallback incurs restrictions like going from avx to sse.

**Comment by rgommers** [comment]
We discussed this a bit in the NumPy optimization team meeting yesterday. It seemed reasonable to everyone to build for fewer target architectures. When selecting the ones to ship, the expectation was that Haswell (first AVX2) and SkylakeX (first AVX512) would be important.

With target `PRESCOTT` (current default build flags on Linux):
```
$ $ CFLAGS="$CFLAGS -fvisibility=protected -Wno-uninitialized" make BUFFERSIZE=20 DYNAMIC_ARCH=1 USE_OPENMP=0 NUM_THREADS=64 OBJCONV=$PWD/objconv/objconv SYMBOLPREFIX=scipy_ LIBNAMEPREFIX=scipy_ FIXED_LIBNAME=1 TARGET=PRESCOTT
$ $ ls -lh libscipy_openblas.so
35M
```

With `DYNAMIC_ARCH` disabled:
```
$ CFLAGS="$CFLAGS -fvisibility=protected -Wno-uninitialized" make BUFFERSIZE=20 DYNAMIC_ARCH=0 USE_OPENMP=0 NUM_THREADS=64 OBJCONV=$PWD/objconv/objconv SYMBOLPREFIX=scipy_ LIBNAMEPREFIX=scipy_ FIXED_LIBNAME=1
$ ls -lh libscipy_openblas.so
15M
```

With a custom selection (Prescott baseline, plus 3 newer architectures):
```
$ CFLAGS="$CFLAGS -fvisibility=protected -Wno-uninitialized" make BUFFERSIZE=20 DYNAMIC_ARCH=1 USE_OPENMP=0 NUM_THREADS=64 OBJCONV=$PWD/objconv/objconv SYMBOLPREFIX=scipy_ LIBNAMEPREFIX=scipy_ FIXED_LIBNAME=1 TARGET=PRESCOTT DYNAMIC_LIST="HASWELL SKYLAKEX SAPPHIRERAPIDS"
$ ls -lh libscipy_openblas.so
21M
```
Note: see `Makefile.system` for details on `DYNAMIC_CORE`/`DYNAMIC_LIST` to see how architectures are selected.

So it's about 1.5 MB shared library size extra per architecture that is built for. The compression factor for the shared library is about 3.5x. Meaning that the current contribution of `libopenblas.so` to x86-64 numpy/scipy wheels is currently ~9.5 MB, and if we'd go from 15 to say 5 architectures, we'd reduce wheel sizes by about 4 MB.

**Comment by rgommers** [comment]
Given the current traffic for numpy/scipy on PyPI, such a 4 MB reduction would saves about 17 PB/year (petabytes - how often do you get to use those:)) of download volume. I think we should make a selection of architectures based on what we know, then do some performance testing, and ship the reduced-size wheels unless we find a serious performance concern.

**Comment by mattip** [comment]
Makes sense to me. We should keep the PRESCOTT target for low-end processors, and add a few others based on some measure of middle-end and high-end processors. The aarch64 wheels, with only a few kernels shipped, are much smaller than the x86_64 ones.

**Comment by rgommers** [comment]
For NumPy we pick different levels per target, making the performance/size tradeoff per set of functions based on benchmarking or knowledge of what instructions are used:
```
Generating multi-targets for "argfunc.dispatch.h" 
  Enabled targets: AVX512_SKX, AVX2, SSE42, baseline
Generating multi-targets for "x86_simd_argsort.dispatch.h" 
  Enabled targets: AVX512_SKX, AVX2
Generating multi-targets for "x86_simd_qsort.dispatch.h" 
  Enabled targets: AVX512_SKX, AVX2
Generating multi-targets for "x86_simd_qsort_16bit.dispatch.h" 
  Enabled targets: AVX512_SPR, AVX512_ICL
Generating multi-targets for "highway_qsort.dispatch.h" 
  Enabled targets: 
Generating multi-targets for "highway_qsort_16bit.dispatch.h" 
  Enabled targets: 
Generating multi-targets for "loops_arithm_fp.dispatch.h" 
  Enabled targets: FMA3__AVX2, baseline
Generating multi-targets for "loops_arithmetic.dispatch.h" 
  Enabled targets: AVX512_SKX, AVX512F, AVX2, SSE41, baseline
...
Generating multi-targets for "_simd.dispatch.h" 
  Enabled targets: SSE42, AVX2, FMA3, FMA3__AVX2, AVX512F, AVX512_SKX, baseline
```
Baseline is SSE3 as the highest level, which matches Prescott.

We should hopefully have some more benchmarking results to decide on this soon.

**Comment by mattip** [comment]
Is there any resolution of a recommended set of `DYNAMIC_LIST=???` that we can add for `x86_64`?

**Comment by mattip** [comment]
I spent some time looking through the wikipedia [page about avx-512](https://en.wikipedia.org/wiki/AVX-512#CPUs_with_AVX-512). It seems there are many more instruction variations than actual chips that support them. AMD Zen 4 (ryzen 7000) has AVX-512f, but it seems Intel has stopped shipping consumer chips with AVX-512 variations. They are available for server (XEON) level processors.

There is also some talk about use of AVX-512 actually harming overall performance: due to thermal and power considerations. Although the vectored operations are faster, they come at a cost.

**Comment by martin-frbg** [comment]
From my (very) limited understanding of Apple products, the only relevant "flavor" of AVX512 support in terms of OpenBLAS' TARGET names would be SKYLAKEX for the 2017 iMac Pro, 2019 Mac Pro and 2020 MacBook Pro.

**Comment by mattip** [comment]
@ev-br ran the [numpy linalg benchmarks](https://github.com/numpy/numpy/blob/main/benchmarks/benchmarks/bench_linalg.py) against all the possible values of `DYNAMIC_CORE` (fo linux x86_64) on a AWS [m5 machine](https://aws.amazon.com/ec2/instance-types/m5/#Features), using a script written by @czgdp1807. [Here](https://github.com/ev-br/numpy-benchmarks-openblas/blob/main/results/benchmarks.output.txt) are the results as text. 

From what I can tell, we can see 5 different groupings with similar performance on these benchmarks:
- `COOPERLAKE`, `SKYLAKEX`, `SAPPHIRERAPIDS` (corresponding to AVX512)
- `HASWELL` (AVX2)
- `SANDYBRIDGE` (SSE4.2, AVX, VT-x, VT-d)
- `NEHALEM`, `ATOM` (SSE4.2, VT-x, VT-d)
- `PENRYN`, `CORE2`, `DUNNINGTON`, `PRESCOTT`, `KATMAI`, `NORTHWOOD`, `COPPERMINE`, `BANIAS` (SSE3)

Does that make sense? Are there other benchmarks we should explore?

Next steps: If we are agreed these are the 5 groups, I should try to make a scipy-openblas wheel using `DYNAMIC_LIST="PRESCOTT NEHALEM SANDYBRIDGE HASWELL SAPPHIRERAPIDS"`. @martin-frbg is that the correct way to specify these groupings? I mean, if I specify `SAPPHIRERAPIDS` will a `COOPERLAKE` or `SKYLAKEX` cpu hit those kernels? Once the wheel is available, we can check size reduction and re-run the benchmarks to see that the performance is similar.

**Comment by martin-frbg** [comment]
The main difference between SkylakeX and the newer AVX512 targets should be availability of BFLOAT16 instructions - _if_ numpy/scipy does not benefit from them, you should stick to SKYLAKEX. Currently Cooperlake and SkylakeX would both fall back "downwards" to Haswell if no SkylakeX support is available (as Sapphire Rapids is the one with the most advanced instruction set, which may not be supported on the older models).

**Comment by ev-br** [comment]
For those who prefer figures to text: https://github.com/ev-br/numpy-benchmarks-openblas/blob/main/viz_perf_arch.svg, generated by https://github.com/ev-br/numpy-benchmarks-openblas/blob/main/viz.benchmark.outputs.ipynb

(basically, the figure is just what Matti said)

**Comment by rgommers** [comment]
That list looks right to me - the only thing I'm not sure about by looking at it is whether ATOM falls back to NEHALEM or not.

**Comment by martin-frbg** [comment]
yes it does (see driver/others/dynamic c), further fallback is to PRESCOTT if NEHALEM is not available

**Comment by mattip** [comment]
@ev-br could you (on the m5 machine)
- download the build artifact `wheels-ubuntu-latest-x86_64-1-manylinux ` from [the PR](https://github.com/MacPython/openblas-libs/actions/runs/10093577459?pr=166)
- unzip it into a temprorary directory
- unzip the wheel inside it as well
- compare the size of the `scipy_openblas64/lib/libscipy_openblas64_.so to the `libscipy_openblas64*.so` in <venv-site-packages>/numpy.libs, it should 21Mb vs. 35Mb
- copy over the new shared object on top of the one in the virtual env (note the name is mangled to make sure the proper shared object is loaded into numpy)
- rerun benchmarks, there should now be 5 clear groupings with no real change in performance.

**Comment by ev-br** [comment]
Here are the relative timings:  https://github.com/ev-br/numpy-benchmarks-openblas/commit/d04e34d9ccfed12fe53bc1de3872b0adfd6bbc1f#diff-369cb62d2763ecc38a28a0ec929890eeb46fa252e7e733871866bded07ff7317
and the raw benchmark data are in this commit: https://github.com/ev-br/numpy-benchmarks-openblas/commit/d04e34d9ccfed12fe53bc1de3872b0adfd6bbc1

Results are generated with pretty much the procedure of https://github.com/MacPython/openblas-libs/issues/144#issuecomment-2251958531, only accounting for the fact that I'm building with `scipy-openblas32`, so I've downloaded and replaced the relevant .so in `dist-packages/scipy-openblas32/libs`. And the size of the .so is indeed about 21Mb.

The relative timings indeed seem to form pretty much the same groups, @czgdp1807 would you be able to double-check 
that absolute timings did not change appreciably between https://github.com/MacPython/openblas-libs/issues/144#issuecomment-2249703099 and https://github.com/ev-br/numpy-benchmarks-openblas/commit/d04e34d9ccfed12fe53bc1de3872b0adfd6bbc1 ?

**Comment by mattip** [comment]
Is there a way to query OpenBLAS and get back the list of dynamic kernels built into the library?

**Comment by martin-frbg** [comment]
No, there is no function for that. The fallback mechanism is supposed to ensure that you always get _some_ runnable kernel for your hardware, and you can set OPENBLAS_VERBOSE to get runtime feedback on which it is. As the list can get quite long (especially on x86_64 with the optional DYNAMIC_OLDER), I would not want to add it to the output of openblas_get_config.

**Comment by rgommers** [comment]
Awesome. @mattip probably still just in time for numpy 2.1.0rc1? That would be very nice to get in.

**Comment by mattip** [comment]
Any new version of the wheels needs aarch64 wheels, which is currently failing. So something like #169 is required to unblock that.

**Comment by martin-frbg** [comment]
can you recheck #169 with Mousius' fix for your gcc10.2 build (and the target list typo corrected) please ?

**Comment by mattip** [comment]
> can you recheck https://github.com/MacPython/openblas-libs/pull/169 with Mousius' fix for your gcc10.2 build (and the target list typo corrected) please ?

That seems to work, thanks

**Comment by czgdp1807** [comment]
Regarding this, I noticed one problem with `bench_linalg.Eindot.time_einsum_ij_jk_a_b` with absolute timings of `COPPERLAKE`. In https://github.com/ev-br/numpy-benchmarks-openblas/blob/main/results/benchmarks.output.txt, I see `1.23024` with a spread of `0.0542`. However in https://github.com/ev-br/numpy-benchmarks-openblas/blob/reduced_kernel_list/results/benchmarks.output.txt, its `1.52858` with a spread of `0.01885`. So overall, a difference of 24% with respect to `main`. I think it's significant. For more detailed results for each of the kernels, I will have to parse the results and compare the differences. I think `main` branch has only `txt` results, correct. Like there are no `.json` files? Analysing results for each of the kernels for both the branches is difficult to do manually (because there are 83 * number_of_kernels comparisons to be made). For `COPPERLAKE` I found the above difference for absolute timings, so there might be more such differences.

**Comment by mattip** [comment]
Hmm. On that benchmark in the many-kernel run the spread is 1:1.12, and on the reduced-kernel run it is 1:1.03. However on other benchmarks, like `time_dot_trans_a_atc`, the spread is similar between the two runs. I wonder why that particular benchmark changed significantly?

**Comment by czgdp1807** [comment]
So I added [this script](https://github.com/czgdp1807/numpy-benchmarks-openblas/blob/main/CompareAndParseMarkdownResults.py) to parse and compare the benchmarking results produced by my repository - https://github.com/czgdp1807/numpy-benchmarks-openblas.

The results in [this gist](https://gist.github.com/czgdp1807/73d431e940c8073f0926a6bb03be3c78).

**Comment by rgommers** [comment]
I can't say I understand the results yet. Two questions:
1. Why are there two numbers under `perf_ratio`? This is hard to interpret for me.
2. Why isn't the ratio 1.0 for the architectures that were kept in this list: `DYNAMIC_LIST="PRESCOTT NEHALEM SANDYBRIDGE HASWELL SKYLAKEX"`? Aren't the identical kernels supposed to be executed for those?

**Comment by czgdp1807** [comment]
So here is the explanation behind the results in [this gist](https://gist.githubusercontent.com/czgdp1807/73d431e940c8073f0926a6bb03be3c78/raw/153d18d1fed6a138442cfd68866963b7300db3c1/numpy-benchmarks-openblas.md).

**Consider the following snippet from the above gist**. First explaining what each tuple containing 2 floating point number means here. The number in each tuple on the left comes from [main branch's results/benchmarks.output.txt](https://github.com/ev-br/numpy-benchmarks-openblas/blob/reduced_kernel_list/results/benchmarks.output.txt) and the numbers on the right comes from [reduced_kernel branch's results/benchmarks.output.txt](https://github.com/ev-br/numpy-benchmarks-openblas/blob/d04e34d9ccfed12fe53bc1de3872b0adfd6bbc1f/results/benchmarks.output.txt). For example `(0.00169936, 0.00198691)` under `mean` for `HASWELL` means `0.00169936` is `mean` from `main` and `0.00198691` is `mean` from `reduced_kernel`. `mean` is nothing but absolute timing. Similarly for `spread` and `perf_ratios`.

Now if you calculate percentage change from `main` to `reduced_kernel` it will come out to be `abs(0.00198691 - 0.00169936)/0.00169936` comes out to be `0.169` or `16.9%`. I hope this is making sense. The threshold is of `10%`. So any absolute timing change of greater than `10%` is included in my `gist`. The percentage is calculated using just `mean`. 

The results in my `gist` basically mean that for each benchmark (in the following snippet its `bench_linalg.Eindot.time_dot_d_dot_b_c`) some kernels' absolute timing deviate by more than a certain threshold. The left one coming from `main` and the right one coming from `reduced_kernel`.

bench_linalg.Eindot.time_dot_d_dot_b_c
| arch           | mean                     | spread                 | perf_ratios        |
|:---------------|:-------------------------|:-----------------------|:-------------------|
| SAPPHIRERAPIDS | (0.00169783, 0.00215896) | (4.24e-05, 3.94e-05)   | (1.0, 1.08659)     |
| HASWELL        | (0.00169936, 0.00198691) | (3.28e-05, 3.865e-05)  | (1.0009, 1.0)      |

**Comment by rgommers** [comment]
Okay, so then I get `mean`, but `perf_ratios` is something different, because it doesn't show that 16.9%. That's still a "difference in performance between the current and the best architecture" - where "best" is still arbitrary based on absolute timings. 

For that gist, if the `mean` column is absolute timing and the average of the mean of the first run (first number in the tuples) and the average of the second run are different like this:

<img width="376" alt="image" src="https://github.com/user-attachments/assets/f6def23d-0665-4312-b129-2f95b9886a6b">

that doesn't mean that performance of the first run is better - it's just variation due to the machine being more loaded or something like that. If so, averaging a few runs should fix that.

* * *

We had something like this already a few months ago (plus the changes after than to order the architecture names on the x-axis always in the same order):

![image](https://github.com/user-attachments/assets/edb39c92-e0c4-40bd-933b-e3c4b0f61b16)

That's what we can draw conclusions from. When a second set of points would be shown for the same benchmark (with the openblas build with 5 kernels), then the data points for the kernels that are still included (e.g., Haswell) should overlap (modulo noise - and if not, something is wrong with the builds), and the ones that were dropped should be slightly slower.  I don't think we can from the current data. 

* * *

I think we can either decide to ignore the absolute timing data, because it's not meaningful for a single run, and just deploy the new builds (unless someone can explain why the code paths taken aren't identical). Or we can redo the benchmarks and generate the desired plots.

**Comment by czgdp1807** [comment]
> For that gist, if the `mean` column is absolute timing and the average of the mean of the first run (first number in the tuples) and the average of the second run are different like this:

So there is no difference between `main` and `reduced_kernel`? I thought that the timings coming from `main` are the ones where we are using all 15 kernels but in `reduced_kernel` we are just using 5 kernels.

**Comment by rgommers** [comment]
> I thought that the timings coming from main are the ones where we are using all 15 kernels but in reduced_kernel we are just using 5 kernels.

Yes indeed, but if both the 15-kernel and 5-kernel builds contain _HASWELL_, then the "mean" result for _HASWELL_ should be identical. Variation in absolute timing is due to something external influencing the absolute timings. It's a cloud environment and the benchmarks for 15 were run far apart from those for 5, so perhaps there was something else going on on the machine. 10% variation isn't strange, but it doesn't mean anything.

**Comment by czgdp1807** [comment]
Only `NEHALEM` is present whose `perf_ratio` exceeds 10% deviation. May be because of some noise should be fine I think. Rest of the 4 kernels in the selected grouping are within 10%.

**Comment by ilayn** [comment]
Thanks for informing me about this @rgommers I did not know this. When I look at my fresh conda installation now, I see 

```
(base) ➜  ~ ll ~/miniforge3/envs/vanilla-scipy/lib/libopenblas*
-rwxr-xr-x. 4 ilayn ilayn 40M Aug 18  2025 /home/ilayn/miniforge3/envs/vanilla-scipy/lib/libopenblasp-r0.3.30.so
lrwxrwxrwx. 1 ilayn ilayn  23 Oct 25 15:52 /home/ilayn/miniforge3/envs/vanilla-scipy/lib/libopenblas.so.0 -> libopenblasp-r0.3.30.so
```

I only did `conda install numpy scipy` I think this is the one that conda pulls. Am I doing something wrong that I do not see 10MB version? 

I am on AMD though in case it matters

**Comment by mattip** [comment]
> I only did conda install numpy scipy

This repo builds the scipyopenblas wheels, I don't think the work is reused by conda in its openblas recipe. So you will only see impact if you use `pip install scipy numpy`.

**Comment by rgommers** [comment]
Indeed. Look on PyPI for `scipy-openblas32` for wheel size, and `pip`/`uv`-install it to see the unpacked size.

**Comment by ilayn** [comment]
Makes sense thanks @mattip
