### ISSUE TITLE
Build for latest OpenBLAS

### ISSUE THREAD

**Issue by mattip** [MacPython/openblas-libs#148]
@tylerjereddy in order to build this repo for a particular OpenBLAS commit, you can make a PR to this repo with an updated OprnBLAS commit hash. There are three places that need to change, grep for COMMIT in the .travis* and .github/* files

Merging that should upload tarballs to the usual places, ready for download by the scipy script (after making a change in that script to match)

**Comment by tylerjereddy** [comment]
Won't it have to be like https://github.com/MacPython/openblas-libs/pull/145, and no merging, because we can't consume the new wheels yet?

**Comment by mattip** [comment]
Kind of, base it off the scipy branch and target that branch in the pr

**Comment by mattip** [comment]
On top of #147

**Comment by mattip** [comment]
Closing, as the 0.3.27 tarballs for SciPy were built.
