### ISSUE TITLE
Space on anaconda.org

### ISSUE THREAD

**Issue by mattip** [MacPython/openblas-libs#32]
We only have 3GB on https://anaconda.org/multibuild-wheels-staging, those with admin permissions can see the usage at https://anaconda.org/multibuild-wheels-staging/settings/storage. Of that 3GB, 1.8 is taken up by artifacts from here. @ogrisel, @tylerjereddy @matthew-brett any ideas?

**Comment by mattip** [comment]
@charris @tylerjereddy can we delete some of the older artifacts?

**Comment by matthew-brett** [comment]
Would Anaconda consent to give us more space?

**Comment by mattip** [comment]
I tried opening a support ticket, but the mail I got back seemed to indicate those are only for users with enterprise (paid) accounts. @ogrisel originally set this up, I don't know how the original contact was made.

**Comment by charris** [comment]
> can we delete some of the older artifacts?

Yes. I think we can keep staging clean except during releases and nightly can be cleaned up after wheels development spurts.
