### ISSUE TITLE
OpenBLAS version number in binaries

### ISSUE THREAD

**Issue by tylerjereddy** [MacPython/openblas-libs#4]
The binaries that are generated from this repo can, in some cases, have OpenBLAS version numbers that are not a reflection of what has actually been built.

Usually in these cases the correct commit hash on the OpenBLAS development branch will be included in the file name despite the incorrect OpenBLAS version specification.

This probably shouldn't happen--especially since we now have programmatic access to a version string directly from openblas get_config(). It causes confusion for reviewers & communication with OpenBLAS team.

**Comment by tylerjereddy** [comment]
This only applies to the file names themselves--we can always know for sure with the usual ctypes calls through get_config(). Still, it can cause confusion.

**Comment by mattip** [comment]
This will be closed when we move entirely to the wheels

**Comment by mattip** [comment]
We have moved to wheels. Closing.
