### ISSUE TITLE
Windows builds on appveyor differ significantly from upstream OpenBLAS

### ISSUE THREAD

**Issue by mattip** [MacPython/openblas-libs#6]
The upstream project builds on windows with [this appveyor](https://github.com/xianyi/OpenBLAS/blob/3f1077ce6f694ded9100e7b4b471b3568f03682e/appveyor.yml) configuration. It is significantly different from the one here. Could we somehow reuse their configuration or even use the binary they [release](https://github.com/xianyi/OpenBLAS/releases)?

**Comment by mattip** [comment]
We might want to try azure pipelines like scikit-learn https://github.com/MacPython/scikit-learn-wheels/blob/master/azure-pipelines.yml which still uses multibuild for linux

**Comment by tylerjereddy** [comment]
I saw that, I looked at Azure yesterday because of the windows issues, but setting up without ownership of the repo was looking annoying. We could move org at some point or get Matthew or whoever to try to add it, but it is just 3 jobs & the migration would invariably take some effort + time limit may still apply.

**Comment by mattip** [comment]
The upstream appveyor builds take ~30 minutes each. https://ci.appveyor.com/project/xianyi/openblas/builds/31006083, ours is twice as long https://ci.appveyor.com/project/tylerjereddy/openblas-libs/builds/31023244

**Comment by tylerjereddy** [comment]
Right, we can look into this at some point; some of it may be the build flags.

**Comment by mattip** [comment]
I think using the Makefiles as we do is fine, the build times on github actions are "only" double the upstream ones, probably because of build flags. Closing.
