### ISSUE TITLE
Consider modern mingw-w64 UCRT build

### ISSUE THREAD

**Issue by matthew-brett** [MacPython/openblas-libs#68]
Building Scipy with Meson, I found I needed to rebuild OpenBLAS with mingw-w64, using the new UCRT linkage.

https://github.com/matthew-brett/openblas-libs/blob/ucrt-build/build_openblas.ps1

In particular, I got the compiler from the [rtools](https://github.com/r-windows/rtools-ucrt), installed with:

```
choco install rtools
```

but that is, I believe, equivalent to the latest mingw-w64 UCRT compiler chain.

Would it be reasonable to use that toolchain for the standard CI compile here?

**Comment by mattip** [comment]
We have moved our windows builds to visual 2017 and are on the cusp of moving to 2019, so as I understand UCRT would be fine.

**Comment by matthew-brett** [comment]
I think I've cracked this one, with #82

**Comment by mattip** [comment]
Closing, #82 was merged
