### ISSUE TITLE
Has the macOS ARM64 compile ever worked?

### ISSUE THREAD

**Issue by matthew-brett** [MacPython/openblas-libs#83]
I am just trying to get the macOS / ARM64 build working, first by fixing the `-m128bit-long-double` compile error : https://github.com/xianyi/OpenBLAS/issues/3659

Once I have put in the recommended fix, I am getting:

```
/Applications/Xcode_12.5.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: ../../libopenblas64_p-r0.3.20.a(ztzrqf.o) cputype (16777228) does not match previous archive members cputype (16777223) (all members must match)
```

See: https://github.com/MacPython/openblas-libs/runs/6985937554?step:7:11737

Before I dive headlong into that sweet refreshing pool, has anyone got the OpenBLAS cross-compile to work?  I couldn't find an example on a very brief look at the Actions outputs.

**Comment by mattip** [comment]
Closing since the 0.3.21 builds are working.
